/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'mysql',
    {
      type: 'category',
      label: '1 基本信息',
      link: {type: 'doc', id: '1/introduction'},
      items: [
        '1/1.1/manual-info',
        {
          type: 'category',
          label: '1.2 MySQL 数据库管理系统概述',
          link: {type: 'doc',id: '1/1.2/what-is'},
          items: [
            '1/1.2/1.2.1/what-is-mysql', 
            '1/1.2/1.2.2/features', 
            '1/1.2/1.2.3/history'
          ],
        },
        '1/1.3/mysql-nutshell',
        '1/1.4/added-deprecated-removed',
        '1/1.5/bug-reports',
        {
          type: 'category',
          label: '1.6 MySQL 标准遵从性',
          link: {type: 'doc',id: '1/1.6/compatibility'},
          items: [
            '1/1.6/1.6.1/extensions-to-ansi', 
            {
              type: 'category',
              label: '1.6.2 MySQL 与标准 SQL 的区别',
              link: {type: 'doc',id: '1/1.6/1.6.2/differences-from-ansi'},
              items: [
                '1/1.6/1.6.2/1.6.2.1/ansi-diff-select-into-table', 
                '1/1.6/1.6.2/1.6.2.2/ansi-diff-update', 
                '1/1.6/1.6.2/1.6.2.3/ansi-diff-foreign-keys',
                '1/1.6/1.6.2/1.6.2.4/ansi-diff-comments'
              ],
            },
            {
              type: 'category',
              label: '1.6.3 MySQL 如何处理约束',
              link: {type: 'doc',id: '1/1.6/1.6.3/constraints'},
              items: [
                '1/1.6/1.6.3/1.6.3.1/constraint-primary-key', 
                '1/1.6/1.6.3/1.6.3.2/constraint-foreign-key', 
                '1/1.6/1.6.3/1.6.3.3/constraint-invalid-data',
                '1/1.6/1.6.3/1.6.3.4/constraint-enum'
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '1.7 MySQL 贡献者',
          link: {type: 'doc',id: '1/1.7/credits'},
          items: [
            '1/1.7/1.7.1/contributors', 
            '1/1.7/1.7.2/documenters-translators', 
            '1/1.7/1.7.3/packages',
            '1/1.7/1.7.5/supporters'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '2 MySQL 的安装和升级',
      link: {type: 'doc',id: '2/installing'},
      items: [
        {
          type: 'category',
          label: '2.1 通用安装指南',
          link: {type: 'doc',id: '2/2.1/general-installation-issues'},
          items: [
            '2/2.1/2.1.1/platform-support', 
            '2/2.1/2.1.2/which-version', 
            '2/2.1/2.1.3/getting-mysql',
            {
              type: 'category',
              label: '2.1.4 使用 MD5 校验和或 GnuPG 验证包完整性',
              link: {type: 'doc',id: '2/2.1/2.1.4/verifying-package-integrity'},
              items: [
                '2/2.1/2.1.4/2.1.4.1/verifying-md5-checksum', 
                '2/2.1/2.1.4/2.1.4.2/checking-gpg-signature', 
                '2/2.1/2.1.4/2.1.4.3/checking-gpg-signature-windows',
                '2/2.1/2.1.4/2.1.4.4/checking-rpm-signature'
              ],
            },
          ],
        },
        '2/2.2/binary-installation', 
        {
          type: 'category',
          label: '2.3 在 Microsoft Windows 上安装 MySQL',
          link: {type: 'doc',id: '2/2.3/windows-installation'},
          items: [
            '2/2.3/2.3.1/windows-installation-layout',
            '2/2.3/2.3.2/windows-choosing-package',
            {
              type: 'category',
              label: '2.3.3 Windows 版 MySQL 安装程序',
              link: {type: 'doc',id: '2/2.3/2.3.3/mysql-installer'},
              items: [
                '2/2.3/2.3.3/2.3.3.1/mysql-installer-setup', 
                '2/2.3/2.3.3/2.3.3.2/mysql-installer-change-path-proc', 
                '2/2.3/2.3.3/2.3.3.3/mysql-installer-workflow',
                '2/2.3/2.3.3/2.3.3.4/mysql-installer-catalog-dashboard',
                '2/2.3/2.3.3/2.3.3.5/MySQLInstallerConsole'
              ],
            },
            {
              type: 'category',
              label: '2.3.4 使用非安装压缩包在 Microsoft Windows 上安装 MySQL',
              link: {type: 'doc',id: '2/2.3/2.3.4/windows-install-archive'},
              items: [
                '2/2.3/2.3.4/2.3.4.1/windows-extract-archive', 
                '2/2.3/2.3.4/2.3.4.2/windows-create-option-file', 
                '2/2.3/2.3.4/2.3.4.3/windows-select-server',
                '2/2.3/2.3.4/2.3.4.4/windows-initialize-data-directory',
                '2/2.3/2.3.4/2.3.4.5/windows-server-first-start',
                '2/2.3/2.3.4/2.3.4.6/windows-start-command-line',
                '2/2.3/2.3.4/2.3.4.7/mysql-installation-windows-path',
                '2/2.3/2.3.4/2.3.4.8/windows-start-service',
                '2/2.3/2.3.4/2.3.4.9/windows-testing'
              ],
            },
            '2/2.3/2.3.5/windows-troubleshooting',
            '2/2.3/2.3.6/windows-postinstallation',
            '2/2.3/2.3.7/windows-restrictions',
          ],
        },
        {
          type: 'category',
          label: '2.4 在 macOS 上安装 MySQL',
          link: {type: 'doc',id: '2/2.4/macos-installation'},
          items: [
            '2/2.4/2.4.1/macos-installation-notes', 
            '2/2.4/2.4.2/macos-installation-pkg', 
            '2/2.4/2.4.3/macos-installation-launchd',
            '2/2.4/2.4.4/macos-installation-prefpane'
          ],
        },
        {
          type: 'category',
          label: '2.5 在 Linux 上安装 MySQL',
          link: {type: 'doc',id: '2/2.5/linux-installation'},
          items: [
            '2/2.5/2.5.1/linux-installation-yum-repo', 
            '2/2.5/2.5.2/linux-installation-apt-repo', 
            '2/2.5/2.5.3/linux-installation-sles-repo',
            '2/2.5/2.5.4/linux-installation-rpm',
            '2/2.5/2.5.5/linux-installation-debian',
            {
              type: 'category',
              label: '2.5.6 使用 Docker 在 Linux 上部署 MySQL',
              link: {type: 'doc',id: '2/2.5/2.5.6/linux-installation-docker'},
              items: [
                '2/2.5/2.5.6/2.5.6.1/docker-mysql-getting-started',
                '2/2.5/2.5.6/2.5.6.2/docker-mysql-more-topics',
              ],
            },
            '2/2.5/2.5.7/linux-installation-native',
            '2/2.5/2.5.8/linux-installation-juju',
            '2/2.5/2.5.9/using-systemd'
          ],
        },
        '2/2.6/uln-installation',
        {
          type: 'category',
          label: '2.7 在 Solaris 上安装 MySQL',
          link: {type: 'doc',id: '2/2.7/solaris-installation'},
          items: [
            '2/2.7/2.7.1/solaris-installation-pkg',
          ],
        },
        '2/2.8/freebsd-installation',
        {
          type: 'category',
          label: '2.9 从源代码安装 MySQL',
          link: {type: 'doc',id: '2/2.9/source-installation'},
          items: [
            '2/2.9/2.9.1/source-installation-methods', 
            '2/2.9/2.9.2/source-installation-prerequisites', 
            '2/2.9/2.9.3/source-installation-layout',
            '2/2.9/2.9.4/installing-source-distribution',
            '2/2.9/2.9.5/installing-development-tree',
            '2/2.9/2.9.6/source-ssl-library-configuration',
            '2/2.9/2.9.7/source-configuration-options',
            '2/2.9/2.9.8/compilation-problems',
            '2/2.9/2.9.9/source-configuration-third-party',
            '2/2.9/2.9.10/source-installation-doxygen'
          ],
        },
        {
          type: 'category',
          label: '2.10 安装后设置和测试',
          link: {type: 'doc',id: '2/2.10/postinstallation'},
          items: [
            '2/2.10/2.10.1/data-directory-initialization', 
            {
              type: 'category',
              label: '2.10.2 启动服务器',
              link: {type: 'doc',id: '2/2.10/2.10.2/starting-server'},
              items: [
                '2/2.10/2.10.2/2.10.2.1/starting-server-troubleshooting', 
              ],
            },
            '2/2.10/2.10.3/testing-server',
            '2/2.10/2.10.4/default-privileges',
            '2/2.10/2.10.5/automatic-start'
          ],
        },
        {
          type: 'category',
          label: '2.11 升级 MySQL',
          link: {type: 'doc',id: '2/2.11/upgrading'},
          items: [
            '2/2.11/2.11.1/upgrade-before-you-begin', 
            '2/2.11/2.11.2/upgrade-paths',
            '2/2.11/2.11.3/upgrading-what-is-upgraded',
            '2/2.11/2.11.4/upgrading-from-previous-series',
            '2/2.11/2.11.5/upgrade-prerequisites',
            '2/2.11/2.11.6/upgrade-binary-package', 
            '2/2.11/2.11.7/updating-yum-repo',
            '2/2.11/2.11.8/updating-apt-repo', 
            '2/2.11/2.11.9/updating-sles-repo',
            '2/2.11/2.11.10/windows-upgrading',
            '2/2.11/2.11.11/upgrade-docker-mysql',
            '2/2.11/2.11.12/upgrade-troubleshooting', 
            '2/2.11/2.11.13/rebuilding-tables',
            '2/2.11/2.11.14/copying-databases'
          ],
        },
        '2/2.12/downgrading',
        {
          type: 'category',
          label: '2.13 Perl 安装说明',
          link: {type: 'doc',id: '2/2.13/perl-support'},
          items: [
            '2/2.13/2.13.1/perl-installation', 
            '2/2.13/2.13.2/activestate-perl', 
            '2/2.13/2.13.3/perl-support-problems'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '3 教程',
      link: {type: 'doc',id: '3/tutorial'},
      items: [
        '3/3.1/connecting-disconnecting', 
        '3/3.2/entering-queries', 
        {
          type: 'category',
          label: '3.3 创建和使用数据库',
          link: {type: 'doc',id: '3/3.3/database-use'},
          items: [
            '3/3.3/3.3.1/creating-database', 
            '3/3.3/3.3.2/creating-tables', 
            '3/3.3/3.3.3/loading-tables',
            {
              type: 'category',
              label: '3.3.4 从表中检索信息',
              link: {type: 'doc',id: '3/3.3/3.3.4/retrieving-data'},
              items: [
                '3/3.3/3.3.4/3.3.4.1/selecting-all',
                '3/3.3/3.3.4/3.3.4.2/selecting-rows',
                '3/3.3/3.3.4/3.3.4.3/selecting-columns',
                '3/3.3/3.3.4/3.3.4.4/sorting-rows',
                '3/3.3/3.3.4/3.3.4.5/date-calculations', 
                '3/3.3/3.3.4/3.3.4.6/working-with-null', 
                '3/3.3/3.3.4/3.3.4.7/pattern-matching', 
                '3/3.3/3.3.4/3.3.4.8/counting-rows', 
                '3/3.3/3.3.4/3.3.4.9/multiple-tables'
              ],
            },
          ],
        },
      ],
    },
  ],
  
};

module.exports = sidebars;
